### ISSUE TITLE
An error occurred during installation。

### ISSUE THREAD

**Issue by Jonyian** [Jacklinkk/Graph_CAVs#2]
Thank you very much, I installed the process from the source code at the end of the first process during the trial installation:
python setup.py develop prompts an error error: docutils 0.16 is installed but docutils<0.20,>=0.18 is required by {'sphinx'} 
Should this be resolved?

**Comment by Jonyian** [comment]
Hi,When I tried to solve the problem, I tried to change the docutils version to 0.18. However, after installing 0.18, I was prompted with other dependency errors.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 6.0.0b2 requires Pygments>=2.12, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-applehelp, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-devhelp, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-htmlhelp>=2.0.0, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-jsmath, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-qthelp, which is not installed.
sphinx 6.0.0b2 requires sphinxcontrib-serializinghtml>=1.1.5, which is not installed.
awscli 1.27.2 requires docutils<0.17,>=0.10, but you have docutils 0.18 which is incompatible.
awscli 1.27.2 requires PyYAML<5.5,>=3.10, but you have pyyaml 6.0 which is incompatible.
sphinx 6.0.0b2 requires Jinja2>=3.0, but you have jinja2 3.0.0rc2 which is incompatible.`

**Comment by Jacklinkk** [comment]
Hello, you can directly try the python file in the "Flow_Test" folder, if the code can run, there is no need to care about the version of "docutils".

**Comment by Jonyian** [comment]
Thank you very much for your reply. After I tried the solution you said, the above problem was solved, but I ran /GRL_Simulation/main" in Pycharm at the end. I tried two files, both prompted a new error, I Paste the error message, ask for help, look forward to your answer, thank you again!
`/home/jon/anaconda3/envs/Graph_CAV/bin/python /home/jon/Graph_CAVs-main/GRL_Simulation/main/main_FigureEight.py 
Traceback (most recent call last):
  File "/home/jon/Graph_CAVs-main/GRL_Simulation/main/main_FigureEight.py", line 99, in <module>
    Graph=Enable_Graph)
  File "/home/jon/Graph_CAVs-main/GRL_Experiment/Exp_FigureEight/FE_TD3.py", line 59, in run
    from GRL_Net.Model_Continuous.DDPG import OUActionNoise, NonGraph_Actor_Model, NonGraph_Critic_Model
  File "/home/jon/Graph_CAVs-main/GRL_Net/Model_Continuous/DDPG.py", line 5, in <module>
    from torch_geometric.nn import GCNConv
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

Process finished with exit code 1
`

`/home/jon/anaconda3/envs/Graph_CAV/bin/python /home/jon/Graph_CAVs-main/GRL_Simulation/main/main_HightwayRamps.py 
Traceback (most recent call last):
  File "/home/jon/Graph_CAVs-main/GRL_Simulation/main/main_HightwayRamps.py", line 150, in <module>
    Graph=Enable_Graph)
  File "/home/jon/Graph_CAVs-main/GRL_Experiment/Exp_HighwayRamps/HR_PPO.py", line 54, in run
    from GRL_Net.Model_Discrete.PPO import NonGraph_Actor_Model, NonGraph_Critic_Model
  File "/home/jon/Graph_CAVs-main/GRL_Net/Model_Discrete/PPO.py", line 4, in <module>
    from torch_geometric.nn import GCNConv
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/jon/anaconda3/envs/Graph_CAV/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

Process finished with exit code 1
`

**Comment by Jonyian** [comment]
Hello, I suddenly thought of a possibility, could it be that our CUDA version is different, mine is CUDA Version: 11.4

**Comment by Jacklinkk** [comment]
Sorry for the late reply, this should be due to a CUDA version error as you say. We recommend installing CUDA 11.3, since the GPU environment of pytorch and pytorch-geometric rely on a specific CUDA version. If you change the CUDA version, it may cause a dependency error.
